#!/bin/bash

set -eu
set -x

usage(){
    cat << EOF
Usage: $0 [--version <version>] [-h|--help]

Build the authd binaries.

Options:
  --version <version>  Version to set in the binary.
  -h, --help           Show this help message and exit.
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            VERSION="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -n "${VERSION:=}" ]; then
    export GOFLAGS="-ldflags=-X=github.com/ubuntu/authd/internal/consts.Version=${VERSION} --mod=vendor -buildmode=pie"
fi

go mod vendor

go generate -C internal/proto/authd
go generate -C pam/internal/gdm

go build -v -o authd ./cmd/authd

go generate -C pam -x -tags pam_debug

go build -C pam -v .

if [ -d ./cmd/authctl ]; then
    go build -v -o authctl ./cmd/authctl
fi

# Some protobuf files get updated but the change depends on the locally installed
# version of protoc (I think) so I don't want to commit it
git checkout "*.pb.go"
