#!/bin/bash

set -euo pipefail

usage(){
    cat << EOF
Usage: $0 [--version <version>] [-h|--help]

Build the broker binary.

Options:
  --version <version>  Version to set in the binary.
  --broker <broker>  The broker to use (oidc, msentraid or google).
  -h, --help           Show this help message and exit.
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            VERSION="$2"
            shift 2
            ;;
        --broker)
            BROKER="$2"
            shift 2
            ;;
        --skip-libhimmelblau)
            SKIP_LIBHIMMELBLAU=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

set -x

if [ -z "${VERSION:-}" ]; then
    # Build the semver tool
    go -C authd-oidc-brokers/tools build -o semver ./semver
    # Get the version
    VERSION=$(SEMVER=authd-oidc-brokers/tools/semver/semver ./snap/scripts/version)
fi

ORIG_PWD=$(pwd)

if [ -n "${BROKER:-}" ]; then
    SQUASHFS_ROOT_DIR="${ORIG_PWD}/authd-${BROKER}-squashfs-root"
fi

go mod vendor

./snap/scripts/prepare-variant --broker "${BROKER:-oidc}"

if [ "${BROKER:-}" = "msentraid" ] && [ -z "${SKIP_LIBHIMMELBLAU:-}" ]; then
    # Build the libhimmelblau binary and header
    RELEASE=1 go -C authd-oidc-brokers generate --tags withmsentraid ./internal/providers/msentraid/himmelblau/...
fi

if [ "${BROKER:-}" != "oidc" ]; then
    export GOFLAGS="--tags=with${BROKER}"
    args="--tags=with${BROKER}"
fi

export GOFLAGS="-ldflags=-X=github.com/canonical/authd/authd-oidc-brokers/internal/consts.Version=${VERSION}"

go -C authd-oidc-brokers build -v -o "authd-${BROKER}" ${args:-} ./cmd/authd-oidc

if [ -d "${SQUASHFS_ROOT_DIR}" ]; then
    mv "authd-oidc-brokers/authd-${BROKER}" "${SQUASHFS_ROOT_DIR}/bin/"
else
    set +x
    echo >&2 "Squashfs root directory ${SQUASHFS_ROOT_DIR} does not exist"
fi
