#!/bin/bash

set -eu
set -x

BUILD_DIR="../build/broker"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LIB_DIR="${SCRIPT_DIR}/lib"

usage(){
    cat << EOF
Usage: $0 [--version <version>] [-h|--help]

Build the broker binary.

Options:
  --version <version>  Version to set in the binary.
  --base-branch <branch> Automatically check out a build branch based on the specified branch with
                         the commits that are not in the main branch cherry-picked.
  -h, --help           Show this help message and exit.
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            VERSION="$2"
            shift 2
            ;;
        --base-branch)
            BASE_BRANCH="$2"
            shift 2
            ;;
        --skip-libhimmelblau)
            SKIP_LIBHIMMELBLAU=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -z "${VERSION:-}" ]; then
    # Build the semver tool
    go -C tools build -o semver ./semver
    # Get the version
    VERSION=$(SEMVER=tools/semver/semver ./snap/version)
fi

if [ -n "${BASE_BRANCH:-}" ]; then
    # shellcheck source=./lib/broker-build.sh
    source "${LIB_DIR}/broker-build.sh"
    create_and_switch_to_broker_build_dir "${BASE_BRANCH}" "${BUILD_DIR}"
fi

go mod vendor

if git grep -q authd-msentraid snap/snapcraft.yaml; then
    args="-tags=withmsentraid -o authd-msentraid"

    if [ -z "${SKIP_LIBHIMMELBLAU:-}" ]; then
        # Build the libhimmelblau binary and header
        RELEASE=1 go generate ./internal/providers/msentraid/himmelblau/...
        if [ -n "${BASE_BRANCH:-}" ]; then
            cp ./internal/providers/msentraid/himmelblau/himmelblau.h "${ORIG_DIR}"/internal/providers/msentraid/himmelblau.h
        fi
    fi
elif git grep -q authd-google snap/snapcraft.yaml; then
    args="-tags=withgoogle -o authd-google"
else
    echo >&2 "Neither authd-msentraid nor authd-google found in snapcraft.yaml."
    exit 1
fi

export GOFLAGS="-ldflags=-X=github.com/ubuntu/authd-oidc-brokers/internal/consts.Version=${VERSION}"
go build -v ${args} ./cmd/authd-oidc
