#!/bin/bash

set -euo pipefail

FILES=(
    snap/snapcraft.yaml
    conf/authd.conf
    internal/consts/authd.go
)

usage() {
    echo "Usage: $0 [--local-branch] [snapcraft options]"
    echo
    echo "Build the msentraid snap."
    echo
    echo "Options:"
    echo "  --local-branch  Use the local msentraid branch instead of origin/msentraid"
    echo
    echo "All other options are passed to snapcraft."
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --local-branch)
            LOCAL_BRANCH=1
            shift
            ;;
        *)
            break
            ;;
    esac
done

# Abort if any of the necessary files have uncommitted changes which
# would be overwritten by the checkout
for file in "${FILES[@]}"; do
    if git diff --quiet -- "$file" && git diff --staged --quiet -- "$file"; then
        continue
    fi

    echo "Error: $file has uncommitted changes"
    exit 1
done

set -x
go mod vendor

if [ -n "${LOCAL_BRANCH:-}" ]; then
    BRANCH=${BRANCH:-msentraid}
else
    BRANCH=${BRANCH:-origin/msentraid}
fi

# Check out the necessary files from the msentraid branch
git checkout --quiet "${BRANCH}" -- "${FILES[@]}"

# Unstage the files so that a simple `git checkout -- <file>` will
# restore it to its original state
git reset --quiet HEAD -- "${FILES[@]}"

# Replace the version in snap/snapcraft.yaml with the branch name
# followed by the commit hash
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
# Snap versions are limited to 32 characters, so we truncate the
# branch name and commit hash to 23 and 8 characters respectively.
VERSION="${BRANCH_NAME:0:23}~$(git rev-parse --short=8 HEAD)"
sed -i 's/^version:.*/version: '"$VERSION"'/' snap/snapcraft.yaml

# On exit, restore the files to their original state
# shellcheck disable=SC2064
trap "git checkout -- ${FILES[*]}" EXIT

# Build the snap
snapcraft "$@"
