#!/bin/bash

set -eu
set -x

BUILD_DIR="../build/broker"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LIB_DIR="${SCRIPT_DIR}/lib"

usage(){
    cat << EOF
Usage: $0 [--version <version>] [-h|--help]

Build the broker binary.

Options:
  --version <version>  Version to set in the binary.
  --msentraid          Build the msentraid broker binary.
  --google             Build the google broker binary.
  --oidc               Build the oidc broker binary.
  --base-branch <branch> Automatically check out a build branch based on the specified branch with
                         the commits that are not in the main branch cherry-picked.
  -h, --help           Show this help message and exit.
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            VERSION="$2"
            shift 2
            ;;
        --msentraid)
            BROKER="msentraid"
            shift
            ;;
        --google)
            BROKER="google"
            shift
            ;;
        --oidc)
            BROKER="oidc"
            shift
            ;;
        --base-branch)
            BASE_BRANCH="$2"
            shift 2
            ;;
        --skip-libhimmelblau)
            SKIP_LIBHIMMELBLAU=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -z "${VERSION:-}" ]; then
    # Build the semver tool
    go -C authd-oidc-brokers/tools build -o semver ./semver
    # Get the version
    VERSION=$(SEMVER=authd-oidc-brokers/tools/semver/semver ./snap/version)
fi

ORIG_PWD=$(pwd)

if [ -n "${BROKER:-}" ]; then
    SQUASHFS_ROOT_DIR="${ORIG_PWD}/authd-${BROKER}-squashfs-root"
fi

go mod vendor

./scripts/prepare-broker-variant-files --broker "${BROKER:-oidc}"

if [ "${BROKER:-}" = "msentraid" ] && [ -z "${SKIP_LIBHIMMELBLAU:-}" ]; then
    # Build the libhimmelblau binary and header
    RELEASE=1 go generate --tags withmsentraid ./internal/providers/msentraid/himmelblau/...
fi

export GOFLAGS="-ldflags=-X=github.com/canonical/authd/authd-oidc-brokers/internal/consts.Version=${VERSION}"
go -C authd-oidc-brokers build -v ${args:-} ./cmd/authd-oidc

if [ -d "${SQUASHFS_ROOT_DIR}" ]; then
    mv "authd-oidc-brokers/authd-${BROKER}" "${SQUASHFS_ROOT_DIR}/bin/"
else
    set +x
    echo >&2 "Squashfs root directory ${SQUASHFS_ROOT_DIR} does not exist"
fi
