#!/bin/sh

journalctl \
    _SYSTEMD_UNIT=authd.service \+ \
    UNIT=authd.service \+ \
    _SYSTEMD_UNIT=snap.authd-msentraid.authd-msentraid.service \+ \
    UNIT=snap.authd-msentraid.authd-msentraid.service \+ \
    SYSLOG_IDENTIFIER=authd-msentraid \+ \
    _SYSTEMD_UNIT=snap.authd-google.authd-google.service \+ \
    UNIT=snap.authd-google.authd-google.service \+ \
    SYSLOG_IDENTIFIER=authd-google \+ \
    _SYSTEMD_UNIT=snap.authd-oidc.authd-oidc.service \+ \
    UNIT=snap.authd-oidc.authd-oidc.service \+ \
    SYSLOG_IDENTIFIER=authd-oidc \+ \
    _COMM=authd-pam \
    "$@"
