#!/bin/bash

set -euo pipefail

usage(){
    cat << EOF
    Usage: $0 [--build-dir] [--skip-build] [--no-lintian] [--release <release>]

Build the authd source deb, extract it and run lrc on it.

Options:
  --build-dir <dir>  Directory to use for building the package. Defaults to ../build/authd.
  --skip-build  Skip building the source package and just run lrc on the existing source package in the build directory.
  --no-lintian  Don't run lintian when building the source package.
  --release <release>  The Ubuntu release to use for the sbuild chroot (default: noble).
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-dir)
            BUILD_DIR="$2"
            shift 2
            ;;
        --skip-build)
            SKIP_BUILD=1
            shift
            ;;
        --no-lintian)
            NO_LINTIAN=1
            shift
            ;;
        --release)
            RELEASE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BUILD_DIR=${BUILD_DIR:-"../build/authd/"}
RELEASE=${RELEASE:-"noble"}

set -x

if [ -z "${SKIP_BUILD:-}" ]; then
     # Build the source package
    "${SCRIPT_DIR}/build-authd-deb" \
      --build-dir "${BUILD_DIR}" \
      ${NO_LINTIAN:+--no-lintian} \
      --only-source \
      --release "${RELEASE}"
fi

# Extract the source package
# shellcheck disable=SC2012
tarball=$(ls -t1 "$(dirname "${BUILD_DIR}")"/authd_*.tar* | head -n1)
rm -rf "${BUILD_DIR}"
tar xf "${tarball}" -C "$(dirname "${BUILD_DIR}")"

# Run lrc on the extracted source package
cd "$(dirname "${BUILD_DIR}")/authd"
lrc
