#!/bin/sh

set -eu
set -x

if ! golangci-lint run; then
    set +x
    echo >&2 "pre-push: Error: golangci-lint failed"
    FAILED=1
fi

# Check if the strings "DO-NOT-PUSH" or "XXX" are present in the diff with main
if git diff main | grep -e DO-NOT-PUSH -e XXX | grep -v "mktemp"; then
    set +x
    echo >&2 "pre-push: Error: Found string DO-NOT-PUSH or XXX"
    FAILED=1
fi

set +x
if [ -n "${FAILED:-}" ]; then
    exit 1
fi
